# Generated by Django 4.2.17 on 2025-04-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_attendance_options_and_more'),
    ]

    operations = [
    ]
