services:
  - type: web
    name: django-emp-app
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: bash -c "python empmanagement/manage.py migrate --noinput && python empmanagement/manage.py collectstatic --noinput && gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHONPATH
        value: ".:./empmanagement"
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "empmanagement.settings"
