services:
  - type: web
    name: django-emp-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd empmanagement && gunicorn empmanagement.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
