services:
  - type: web
    name: django-emp-app
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHONPATH
        value: ".:./empmanagement"
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "empmanagement.settings"
      - key: DATABASE_URL
        fromDatabase:
          name: django-emp-db
          property: connectionString

  - type: postgresql
    name: django-emp-db
    plan: free
    ipAllowList: []

